name: ArdaGone
version: '${project.version}'
main: org.laser.ardagone.ArdaGone
api-version: '1.20'
commands:
  test:
  createcharacter:
  listcharacters:
  checkchars:
  character:
  selectcharacter:
  getchar:
  fornite:
  savespawnpoint:
  randomspawn:
  join:
  leave: