name: ArdaGone
version: '1.20.4'
main: org.laser.ardagone.ArdaGone
api-version: '1.20'
commands:
  test:
  createcharacter:
  listcharacters:
  checkchars:
  character:
  selectcharacter:
  getchar:
  zone:
  stopfog:
  startfog:
  savespawnpoint:
  randomspawn:
  join:
  leave:
  gui: